# -*- mode: ruby -*-
# vi: set ft=ruby :

DIR = File.dirname(__FILE__)

Vagrant.configure(2) do |config|
  config.vm.box = "brownell/xenial64lemp"
  config.vm.box_check_update = true

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "forwarded_port", guest:80, host: 8080
  config.vm.network "private_network", ip: "192.168.12.12"
  config.vm.hostname = "realtimeforms.local"

  # Expose MySQL port
  config.vm.network "forwarded_port", guest: 3306, host: 6306

  # Expose Swagger-UI port
  config.vm.network "forwarded_port", guest: 70, host: 7070

  config.hostsupdater.aliases = []
  config.hostsupdater.aliases += ["realtimeforms.local", "www.realtimeforms.local"]

  config.vm.synced_folder DIR, "/var/www/real-time-forms/", id: "vagrant-root", :owner => "vagrant", :group => "www-data"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
  end

  # Get Swagger-UI Docker image
  config.vm.provision "docker", images: ["swaggerapi/swagger-ui"]

  # Run Swagger-UI on port 70 (guest) and 7070 (host)
  config.vm.provision "docker" do |d|
    d.run "swaggerapi/swagger-ui",
      cmd: "busybox -l",
      args: "-p 70:7070 -e SWAGGER_JSON='/var/www/real-time-forms/real-time-forms-api/doc/swagger.json' -v '/vagrant:/var/www/real-time-forms/real-time-forms-api/'"
  end

end