<?php
    define("DB_HOST","192.168.0.215");
    define("DB_USER","ELEGANT_MVC_ROOT_USER");
    define("DB_PASS","ELEGANT_MVC_ROOT_P@SSW0RD123!");
    define("DB_NAME","ELEGANT_MVC_DB");

    // SELECT user,host FROM mysql.user;
    
// CREATE USER 'ELEGANT_MVC_ROOT_USER'@'192.168.0.215' IDENTIFIED BY 'ELEGANT_MVC_ROOT_P@SSW0RD123!';
// GRANT ALL PRIVILEGES ON *.* TO 'ELEGANT_MVC_ROOT_USER'@'192.168.0.215';



?>