Vagrant.configure("2") do |config|
  config.vm.box = "brownell/xenial64lemp"
  config.vm.network "forwarded_port", guest: 80, host: 8080

  # this is overwritting our default...
  config.vm.synced_folder "../../etc/nginx/sites-available", "/etc/nginx/sites-available"


  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", path: "provision.sh"
end
